# Generated by Django 4.2.2 on 2023-06-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0002_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100, null=True)),
                ('Password', models.CharField(default=None, max_length=100, null=True)),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('Age', models.CharField(default=None, max_length=200, null=True)),
                ('Phone', models.CharField(default=None, max_length=100, null=True)),
                ('Email', models.CharField(default=None, max_length=100, null=True)),
                ('Address', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'userDetails',
            },
        ),
    ]
