# Generated by Django 4.2.2 on 2023-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
