# Generated by Django 4.2.2 on 2023-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0005_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=None, max_length=100)),
                ('comment', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
