# Generated by Django 4.2.2 on 2023-06-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom_App.userdetails'),
        ),
    ]
