# Generated by Django 4.2.2 on 2023-06-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0007_alter_comments_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
