# Generated by Django 4.2.2 on 2023-07-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0008_comments_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='Status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
