# Generated by Django 4.2.2 on 2023-07-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0009_alter_userorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='User_Status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
