# Generated by Django 4.2.2 on 2023-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0010_userorder_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(default=None, max_length=100)),
                ('Query', models.CharField(default=None, max_length=300)),
                ('Answer', models.CharField(default=None, max_length=300)),
            ],
            options={
                'db_table': 'UserFeedback',
            },
        ),
    ]
