# Generated by Django 4.2.2 on 2023-07-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0011_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='Answer',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='Query',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='User_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
